// ============================================================================
// NETS Enterprise Lead Management — CRM Service (Mock)
// ============================================================================
// Simulates API integration with the future enterprise CRM (e.g. Hubspot, Salesforce).
// ============================================================================

import { API_URL } from '../config/api'

export interface CRMSubmissionResponse {
  success: boolean
  leadId?: string
  error?: string
}

class CRMService {
  /**
   * Submit a new lead to the CRM.
   * This structure strictly follows the Phase 6 Enterprise Data Model.
   * 
   * @param payload The structured CRM Quotation Payload generated by the store
   */
  public async submitLead(payload: any): Promise<CRMSubmissionResponse> {
    try {
      const response = await fetch(`${API_URL}/leads`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      })

      if (response.ok) {
        const json = await response.json()
        const leadData = json.data?.lead || json.data
        return {
          success: true,
          leadId: leadData?.leadId || leadData?.leadReference || `LEAD-${Date.now().toString().slice(-6)}`,
        }
      }
    } catch (err) {
      console.warn('⚠️ [CRM SERVICE] Backend REST API unreachable, falling back to local queue mode:', err)
    }

    // Fallback simulation if API is unreachable
    return new Promise((resolve) => {
      setTimeout(() => {
        const mockLeadId = `LEAD-${Date.now().toString().slice(-6)}`
        console.log('🚀 [CRM SERVICE] LEAD SUBMITTED (FALLBACK MODE)')
        resolve({
          success: true,
          leadId: mockLeadId
        })
      }, 600)
    })
  }

  /**
   * Fire an analytics event for business intelligence.
   */
  public trackEvent(eventName: string, eventData: any): void {
    console.log(`📊 [ANALYTICS] ${eventName}`, eventData)
  }
}

export const crmService = new CRMService()
